import type { AppManifest } from '@ankhorage/contracts';

const authRequired = { required: true } as const;

export const nutritionCatalogScanData = {
  apis: {
    nutritionProducts: {
      id: 'nutritionProducts',
      kind: 'generated',
      preset: 'crud',
      label: 'Nutrition products',
      description: 'Published product catalog entries available to signed-in challenge scanners.',
      basePath: '/v1/nutrition/products',
      auth: authRequired,
      resource: {
        kind: 'collection',
        collection: {
          name: 'nutrition_products',
          schema: 'public',
          primaryKey: 'id',
          fields: [
            { name: 'id', type: 'uuid', required: true },
            { name: 'barcode', type: 'text', required: true, unique: true },
            { name: 'name', type: 'text', required: true },
            { name: 'brand', type: 'text' },
            { name: 'quantity', type: 'text' },
            { name: 'country', type: 'text', required: true, defaultValue: 'CH' },
            { name: 'nutritionFacts', type: 'json' },
            { name: 'confidence', type: 'number', defaultValue: 0 },
            { name: 'createdAt', type: 'datetime', required: true },
            { name: 'updatedAt', type: 'datetime', required: true },
          ],
        },
      },
      endpoints: [
        {
          id: 'listNutritionProducts',
          label: 'List products',
          method: 'GET',
          path: '/',
          intent: 'list',
          auth: authRequired,
        },
        {
          id: 'getNutritionProductById',
          label: 'Get product',
          method: 'GET',
          path: '/:id',
          intent: 'read',
          auth: authRequired,
        },
        {
          id: 'getNutritionProductByBarcode',
          label: 'Get product by barcode',
          method: 'GET',
          path: '/by-barcode/:barcode',
          intent: 'read',
          auth: authRequired,
        },
      ],
    },
    nutritionProductCaptures: {
      id: 'nutritionProductCaptures',
      kind: 'generated',
      preset: 'crud',
      label: 'Nutrition product captures',
      description: 'Queued missing-product submissions created by signed-in scanners.',
      basePath: '/v1/nutrition/products/captures',
      auth: authRequired,
      resource: {
        kind: 'collection',
        collection: {
          name: 'nutrition_product_captures',
          schema: 'public',
          primaryKey: 'id',
          fields: [
            { name: 'id', type: 'uuid', required: true },
            { name: 'userId', type: 'uuid', required: true },
            { name: 'barcode', type: 'text', required: true },
            { name: 'productName', type: 'text', required: true },
            { name: 'brand', type: 'text' },
            { name: 'quantity', type: 'text' },
            { name: 'storeChain', type: 'text' },
            { name: 'country', type: 'text', required: true, defaultValue: 'CH' },
            { name: 'status', type: 'text', required: true, defaultValue: 'queued' },
            { name: 'photoRefs', type: 'json' },
            { name: 'clientCapturedAt', type: 'datetime', required: true },
            { name: 'createdAt', type: 'datetime', required: true },
            { name: 'updatedAt', type: 'datetime', required: true },
          ],
        },
      },
      endpoints: [
        {
          id: 'listNutritionProductCaptures',
          label: 'List captures',
          method: 'GET',
          path: '/',
          intent: 'list',
          auth: authRequired,
        },
        {
          id: 'createNutritionProductCapture',
          label: 'Create capture',
          method: 'POST',
          path: '/',
          intent: 'create',
          auth: authRequired,
        },
      ],
    },
    nutritionScanChallenges: {
      id: 'nutritionScanChallenges',
      kind: 'generated',
      preset: 'crud',
      label: 'Nutrition scan challenges',
      description: 'Friends-only challenge windows, scoring rules, and leaderboard context.',
      basePath: '/v1/nutrition/challenges',
      auth: authRequired,
      resource: {
        kind: 'collection',
        collection: {
          name: 'nutrition_scan_challenges',
          schema: 'public',
          primaryKey: 'id',
          fields: [
            { name: 'id', type: 'uuid', required: true },
            { name: 'title', type: 'text', required: true },
            { name: 'description', type: 'text' },
            { name: 'startsAt', type: 'datetime', required: true },
            { name: 'endsAt', type: 'datetime', required: true },
            { name: 'isActive', type: 'boolean', required: true, defaultValue: true },
            { name: 'scoringRules', type: 'json' },
            { name: 'createdAt', type: 'datetime', required: true },
          ],
        },
      },
      endpoints: [
        {
          id: 'listNutritionScanChallenges',
          label: 'List challenges',
          method: 'GET',
          path: '/',
          intent: 'list',
          auth: authRequired,
        },
        {
          id: 'getCurrentNutritionScanChallenge',
          label: 'Get current challenge',
          method: 'GET',
          path: '/current',
          intent: 'read',
          auth: authRequired,
        },
        {
          id: 'getCurrentNutritionScanLeaderboard',
          label: 'Get current leaderboard',
          method: 'GET',
          path: '/current/leaderboard',
          intent: 'read',
          auth: authRequired,
        },
      ],
    },
    nutritionScanEvents: {
      id: 'nutritionScanEvents',
      kind: 'generated',
      preset: 'crud',
      label: 'Nutrition scan events',
      description: 'Signed-in scanner actions used for points, duplicate rules, and rankings.',
      basePath: '/v1/nutrition/scan-events',
      auth: authRequired,
      resource: {
        kind: 'collection',
        collection: {
          name: 'nutrition_scan_events',
          schema: 'public',
          primaryKey: 'id',
          fields: [
            { name: 'id', type: 'uuid', required: true },
            { name: 'challengeId', type: 'uuid', required: true },
            { name: 'userId', type: 'uuid', required: true },
            { name: 'barcode', type: 'text', required: true },
            { name: 'productId', type: 'uuid' },
            { name: 'captureId', type: 'uuid' },
            { name: 'eventType', type: 'text', required: true },
            { name: 'points', type: 'number', required: true, defaultValue: 0 },
            { name: 'clientCapturedAt', type: 'datetime', required: true },
            { name: 'createdAt', type: 'datetime', required: true },
          ],
        },
      },
      endpoints: [
        {
          id: 'listNutritionScanEvents',
          label: 'List scan events',
          method: 'GET',
          path: '/',
          intent: 'list',
          auth: authRequired,
        },
        {
          id: 'createNutritionScanEvent',
          label: 'Create scan event',
          method: 'POST',
          path: '/',
          intent: 'create',
          auth: authRequired,
        },
      ],
    },
  },
} satisfies AppManifest['data'];
