graph LR
  module_package_json["package.json"]
  module_src_authoring_compose_category_manifest_ts["src/authoring/compose-category-manifest.ts"]
  module_src_authoring_create_manifest_shell_ts["src/authoring/create-manifest-shell.ts"]
  module_src_authoring_splash_screen_ts["src/authoring/splash-screen.ts"]
  module_src_catalog_ts["src/catalog.ts"]
  module_src_cli_index_ts["src/cli/index.ts"]
  module_src_cli_standalone_ts["src/cli/standalone.ts"]
  module_src_commandContext_ts["src/commandContext.ts"]
  module_src_commands_ts["src/commands.ts"]
  module_src_design_category_source_ts["src/design/category-source.ts"]
  module_src_design_category_theme_ts["src/design/category-theme.ts"]
  module_src_design_category_types_ts["src/design/category-types.ts"]
  module_src_design_tone_catalog_ts["src/design/tone-catalog.ts"]
  module_src_fixtures_oauth_ts["src/fixtures/oauth.ts"]
  module_src_index_ts["src/index.ts"]
  module_src_internal_defaults_ts["src/internal/defaults.ts"]
  module_src_packageMetadata_ts["src/packageMetadata.ts"]
  module_src_presets_category_presets_ts["src/presets/category-presets.ts"]
  module_src_projectSeed_ts["src/projectSeed.ts"]
  module_src_templates_catalog_generated_ts["src/templates/catalog.generated.ts"]
  module_src_templates_catalog_ts["src/templates/catalog.ts"]
  module_src_templates_categories_education_learning_sharkprey_createAppManifest_ts["src/templates/categories/education-learning/sharkprey/createAppManifest.ts"]
  module_src_templates_categories_lifestyle_stillpath_createAppManifest_ts["src/templates/categories/lifestyle/stillpath/createAppManifest.ts"]
  module_src_templateSelector_ts["src/templateSelector.ts"]
  export_ACCENT_TONE_FAMILIES["ACCENT_TONE_FAMILIES"]
  module_src_design_tone_catalog_ts --> export_ACCENT_TONE_FAMILIES
  export_ACCENT_TONE_TARGETS["ACCENT_TONE_TARGETS"]
  module_src_design_tone_catalog_ts --> export_ACCENT_TONE_TARGETS
  export_AccentToneFamily["AccentToneFamily"]
  module_src_design_tone_catalog_ts --> export_AccentToneFamily
  export_APP_CATEGORIES["APP_CATEGORIES"]
  module_node_modules__ankhorage_contracts_dist_types_d_ts --> export_APP_CATEGORIES
  export_AppCategory["AppCategory"]
  module_node_modules__ankhorage_contracts_dist_types_d_ts --> export_AppCategory
  export_assertTemplateManifestReady["assertTemplateManifestReady"]
  module_src_authoring_compose_category_manifest_ts --> export_assertTemplateManifestReady
  export_assertTemplateManifestReady -.-> export_CategoryAppManifestComposition
  export_CATEGORY_PRESET_RECONCILIATION["CATEGORY_PRESET_RECONCILIATION"]
  module_src_presets_category_presets_ts --> export_CATEGORY_PRESET_RECONCILIATION
  export_CATEGORY_PRESETS["CATEGORY_PRESETS"]
  module_src_presets_category_presets_ts --> export_CATEGORY_PRESETS
  export_CategoryAppManifestComposition["CategoryAppManifestComposition"]
  module_src_authoring_compose_category_manifest_ts --> export_CategoryAppManifestComposition
  export_CategoryAppManifestComposition -.-> export_TemplateAuthoringState
  export_CategoryAppManifestComposition -.-> export_TemplateCompositionDiagnostic
  export_CategoryAppManifestComposition -.-> export_TemplateCompositionStatus
  export_CategoryDesignDiagnostic["CategoryDesignDiagnostic"]
  module_src_design_category_theme_ts --> export_CategoryDesignDiagnostic
  export_CategoryDesignDiagnostic -.-> export_CategoryDesignDiagnosticCode
  export_CategoryDesignDiagnosticCode["CategoryDesignDiagnosticCode"]
  module_src_design_category_theme_ts --> export_CategoryDesignDiagnosticCode
  export_CategoryDesignOverrides["CategoryDesignOverrides"]
  module_src_design_category_theme_ts --> export_CategoryDesignOverrides
  export_CategoryDesignOverrides -.-> export_ThemeMode
  export_CategoryPreset["CategoryPreset"]
  module_src_design_category_types_ts --> export_CategoryPreset
  export_CategoryPresetFieldReconciliation["CategoryPresetFieldReconciliation"]
  module_src_design_category_types_ts --> export_CategoryPresetFieldReconciliation
  export_CategoryPresetFieldReconciliation -.-> export_CategoryPresetReconciliationDecision
  export_CategoryPresetReconciliationDecision["CategoryPresetReconciliationDecision"]
  module_src_design_category_types_ts --> export_CategoryPresetReconciliationDecision
  export_CategoryPresetReconciliationReport["CategoryPresetReconciliationReport"]
  module_src_design_category_types_ts --> export_CategoryPresetReconciliationReport
  export_CategoryPresetReconciliationReport -.-> export_CategoryPresetFieldReconciliation
  export_compileCategoryDesign["compileCategoryDesign"]
  module_src_design_category_theme_ts --> export_compileCategoryDesign
  export_compileCategoryDesign -.-> export_CategoryDesignOverrides
  export_compileCategoryDesign -.-> export_CompiledCategoryDesign
  export_CompiledCategoryDesign["CompiledCategoryDesign"]
  module_src_design_category_theme_ts --> export_CompiledCategoryDesign
  export_CompiledCategoryDesign -.-> export_CategoryDesignDiagnostic
  export_CompiledCategoryDesign -.-> export_CategoryPreset
  export_CompiledCategoryDesign -.-> export_ThemeMode
  export_CompiledCategoryDesign -.-> export_TonePairDefinition
  export_composeCategoryAppManifest["composeCategoryAppManifest"]
  module_src_authoring_compose_category_manifest_ts --> export_composeCategoryAppManifest
  export_composeCategoryAppManifest -.-> export_CategoryAppManifestComposition
  export_composeCategoryAppManifest -.-> export_ComposeCategoryAppManifestInput
  export_ComposeCategoryAppManifestInput["ComposeCategoryAppManifestInput"]
  module_src_authoring_compose_category_manifest_ts --> export_ComposeCategoryAppManifestInput
  export_ComposeCategoryAppManifestInput -.-> export_CategoryDesignOverrides
  export_ComposeCategoryAppManifestInput -.-> export_TemplateAuthoringState
  export_createTemplateArtifact["createTemplateArtifact"]
  module_src_templates_catalog_ts --> export_createTemplateArtifact
  export_createTemplateArtifact -.-> export_AppCategory
  export_createTemplateArtifact -.-> export_TemplateArtifact
  export_DESIGN_DENSITIES["DESIGN_DENSITIES"]
  module_src_design_category_types_ts --> export_DESIGN_DENSITIES
  export_DESIGN_SHAPES["DESIGN_SHAPES"]
  module_src_design_category_types_ts --> export_DESIGN_SHAPES
  export_DesignDensity["DesignDensity"]
  module_src_design_category_types_ts --> export_DesignDensity
  export_DesignShape["DesignShape"]
  module_src_design_category_types_ts --> export_DesignShape
  export_FOUNDATION_TONE_FAMILIES["FOUNDATION_TONE_FAMILIES"]
  module_src_design_tone_catalog_ts --> export_FOUNDATION_TONE_FAMILIES
  export_FOUNDATION_TONE_TARGETS["FOUNDATION_TONE_TARGETS"]
  module_src_design_tone_catalog_ts --> export_FOUNDATION_TONE_TARGETS
  export_FoundationToneFamily["FoundationToneFamily"]
  module_src_design_tone_catalog_ts --> export_FoundationToneFamily
  export_listOAuthFixtures["listOAuthFixtures"]
  module_src_fixtures_oauth_ts --> export_listOAuthFixtures
  export_listOAuthFixtures -.-> export_OAuthFixtureDefinition
  export_listTemplates["listTemplates"]
  module_src_templates_catalog_ts --> export_listTemplates
  export_listTemplates -.-> export_TemplateCatalogEntry
  export_OAUTH_CALLBACK_ROUTE["OAUTH_CALLBACK_ROUTE"]
  module_src_fixtures_oauth_ts --> export_OAUTH_CALLBACK_ROUTE
  export_OAUTH_FIXTURE_IDS["OAUTH_FIXTURE_IDS"]
  module_src_fixtures_oauth_ts --> export_OAUTH_FIXTURE_IDS
  export_OAuthFixtureDefinition["OAuthFixtureDefinition"]
  module_src_fixtures_oauth_ts --> export_OAuthFixtureDefinition
  export_OAuthFixtureId["OAuthFixtureId"]
  module_src_fixtures_oauth_ts --> export_OAuthFixtureId
  export_resolveCategoryDesignPreset["resolveCategoryDesignPreset"]
  module_src_design_category_theme_ts --> export_resolveCategoryDesignPreset
  export_resolveCategoryDesignPreset -.-> export_CategoryDesignOverrides
  export_resolveCategoryDesignPreset -.-> export_ResolvedCategoryDesignPreset
  export_ResolvedCategoryDesignPreset["ResolvedCategoryDesignPreset"]
  module_src_design_category_theme_ts --> export_ResolvedCategoryDesignPreset
  export_ResolvedCategoryDesignPreset -.-> export_CategoryDesignDiagnostic
  export_ResolvedCategoryDesignPreset -.-> export_CategoryPreset
  export_ResolvedCategoryDesignPreset -.-> export_ThemeMode
  export_ResolvedCategoryDesignPreset -.-> export_TonePairDefinition
  export_resolveOAuthFixture["resolveOAuthFixture"]
  module_src_fixtures_oauth_ts --> export_resolveOAuthFixture
  export_resolveOAuthFixture -.-> export_OAuthFixtureDefinition
  export_resolveTemplate["resolveTemplate"]
  module_src_templates_catalog_ts --> export_resolveTemplate
  export_resolveTemplate -.-> export_TemplateCatalogEntry
  export_resolveTonePair["resolveTonePair"]
  module_src_design_tone_catalog_ts --> export_resolveTonePair
  export_resolveTonePair -.-> export_TonePairDefinition
  export_SplashScreenResizeMode["SplashScreenResizeMode"]
  module_node_modules__ankhorage_contracts_dist_types_d_ts --> export_SplashScreenResizeMode
  export_SplashScreenSpec["SplashScreenSpec"]
  module_node_modules__ankhorage_contracts_dist_types_d_ts --> export_SplashScreenSpec
  export_SplashScreenSpec -.-> export_SplashScreenResizeMode
  export_TemplateArtifact["TemplateArtifact"]
  module_src_templates_catalog_ts --> export_TemplateArtifact
  export_TemplateArtifact -.-> export_TemplateImageAsset
  export_TemplateAuthoringState["TemplateAuthoringState"]
  module_src_authoring_compose_category_manifest_ts --> export_TemplateAuthoringState
  export_TemplateCatalogEntry["TemplateCatalogEntry"]
  module_src_templates_catalog_ts --> export_TemplateCatalogEntry
  export_TemplateCompositionDiagnostic["TemplateCompositionDiagnostic"]
  module_src_authoring_compose_category_manifest_ts --> export_TemplateCompositionDiagnostic
  export_TemplateCompositionDiagnostic -.-> export_TemplateCompositionDiagnosticCode
  export_TemplateCompositionDiagnosticCode["TemplateCompositionDiagnosticCode"]
  module_src_authoring_compose_category_manifest_ts --> export_TemplateCompositionDiagnosticCode
  export_TemplateCompositionStatus["TemplateCompositionStatus"]
  module_src_authoring_compose_category_manifest_ts --> export_TemplateCompositionStatus
  export_TemplateDefinition["TemplateDefinition"]
  module_src_templates_catalog_ts --> export_TemplateDefinition
  export_TemplateImageAsset["TemplateImageAsset"]
  module_src_templates_catalog_ts --> export_TemplateImageAsset
  export_ThemeMode["ThemeMode"]
  module_src_design_tone_catalog_ts --> export_ThemeMode
  export_TONE_PAIR_CATALOG["TONE_PAIR_CATALOG"]
  module_src_design_tone_catalog_ts --> export_TONE_PAIR_CATALOG
  export_TonePairClassification["TonePairClassification"]
  module_src_design_tone_catalog_ts --> export_TonePairClassification
  export_TonePairDefinition["TonePairDefinition"]
  module_src_design_tone_catalog_ts --> export_TonePairDefinition
  export_TonePairDefinition -.-> export_ThemeMode
  export_TonePairDefinition -.-> export_TonePairClassification
  export_TonePairDefinition -.-> export_ToneTarget
  export_TonePairId["TonePairId"]
  module_src_design_tone_catalog_ts --> export_TonePairId
  export_ToneTarget["ToneTarget"]
  module_src_design_tone_catalog_ts --> export_ToneTarget
  export_validateTemplateManifest["validateTemplateManifest"]
  module_src_authoring_compose_category_manifest_ts --> export_validateTemplateManifest
  export_validateTemplateManifest -.-> export_CategoryAppManifestComposition
  export_validateTemplateManifest -.-> export_TemplateAuthoringState
