import type { AppCategory, ThemeConfig } from '@ankhorage/contracts';

export { APP_CATEGORIES } from '@ankhorage/contracts';

export interface CategoryPreset {
  label: string;
  defaultName: string;
  defaultSlug: string;
  primaryColor: string;
  harmony: ThemeConfig['light']['harmony'];
  summary: string;
  focusAreas: readonly [string, string, string];
}

function createPreset(config: CategoryPreset): CategoryPreset {
  return config;
}

export const CATEGORY_PRESETS: Record<AppCategory, CategoryPreset> = {
  books_reading: createPreset({
    label: 'Books & Reading',
    defaultName: 'Books & Reading',
    defaultSlug: 'books-reading-app',
    primaryColor: '#8B4513',
    harmony: 'analogous',
    summary: 'reading lists, reviews, recommendations, and subscriptions',
    focusAreas: ['Reading queue', 'Featured picks', 'Community notes'],
  }),
  business_productivity: createPreset({
    label: 'Business & Productivity',
    defaultName: 'Business & Productivity',
    defaultSlug: 'business-productivity-app',
    primaryColor: '#1D4ED8',
    harmony: 'analogous',
    summary: 'team coordination, goals, and execution tracking',
    focusAreas: ['Active projects', 'Weekly priorities', 'Team updates'],
  }),
  developer_tools: createPreset({
    label: 'Developer Tools',
    defaultName: 'Developer Tools',
    defaultSlug: 'developer-tools-app',
    primaryColor: '#7C3AED',
    harmony: 'triadic',
    summary: 'release workflows, observability, and engineering operations',
    focusAreas: ['Build status', 'Incident queue', 'Developer settings'],
  }),
  education_learning: createPreset({
    label: 'Education & Learning',
    defaultName: 'Education & Learning',
    defaultSlug: 'education-learning-app',
    primaryColor: '#4338CA',
    harmony: 'analogous',
    summary: 'courses, practice loops, and learner progress',
    focusAreas: ['Current lessons', 'Practice plan', 'Milestone tracking'],
  }),
  entertainment_media: createPreset({
    label: 'Entertainment & Media',
    defaultName: 'Entertainment & Media',
    defaultSlug: 'entertainment-media-app',
    primaryColor: '#F97316',
    harmony: 'complementary',
    summary: 'content discovery, watchlists, and editorial highlights',
    focusAreas: ['Featured releases', 'Continue watching', 'Trending topics'],
  }),
  finance_money: createPreset({
    label: 'Finance & Money',
    defaultName: 'Finance & Money',
    defaultSlug: 'finance-money-app',
    primaryColor: '#15803D',
    harmony: 'analogous',
    summary: 'balances, budgeting, and financial operations',
    focusAreas: ['Cash overview', 'Budget health', 'Upcoming activity'],
  }),
  food_drink: createPreset({
    label: 'Food & Drink',
    defaultName: 'Food & Drink',
    defaultSlug: 'food-drink-app',
    primaryColor: '#EA580C',
    harmony: 'analogous',
    summary: 'menus, ordering, and loyalty experiences',
    focusAreas: ['Popular items', 'Order flow', 'Rewards status'],
  }),
  games: createPreset({
    label: 'Games',
    defaultName: 'Games',
    defaultSlug: 'games-app',
    primaryColor: '#7C3AED',
    harmony: 'splitComplementary',
    summary: 'quests, progression, and player engagement loops',
    focusAreas: ['Daily quests', 'Progression', 'Social challenges'],
  }),
  graphics_design: createPreset({
    label: 'Graphics & Design',
    defaultName: 'Graphics & Design',
    defaultSlug: 'graphics-design-app',
    primaryColor: '#9333EA',
    harmony: 'triadic',
    summary: 'creative assets, reviews, and delivery workflows',
    focusAreas: ['Current briefs', 'Asset review', 'Brand tokens'],
  }),
  health_fitness: createPreset({
    label: 'Health & Fitness',
    defaultName: 'Health & Fitness',
    defaultSlug: 'health-fitness-app',
    primaryColor: '#059669',
    harmony: 'analogous',
    summary: 'habits, activity tracking, and coaching plans',
    focusAreas: ['Today plan', 'Progress rings', 'Recovery status'],
  }),
  kids_family: createPreset({
    label: 'Kids & Family',
    defaultName: 'Kids & Family',
    defaultSlug: 'kids-family-app',
    primaryColor: '#F97316',
    harmony: 'splitComplementary',
    summary: 'safe discovery, routines, and shared family coordination',
    focusAreas: ['Daily routines', 'Favorites', 'Parent controls'],
  }),
  lifestyle: createPreset({
    label: 'Lifestyle',
    defaultName: 'Lifestyle',
    defaultSlug: 'lifestyle-app',
    primaryColor: '#DB2777',
    harmony: 'analogous',
    summary: 'memberships, routines, and curated recommendations',
    focusAreas: ['Personal dashboard', 'Saved lists', 'Upcoming plans'],
  }),
  medical: createPreset({
    label: 'Medical',
    defaultName: 'Medical',
    defaultSlug: 'medical-app',
    primaryColor: '#0369A1',
    harmony: 'analogous',
    summary: 'care coordination, intake, and patient communication',
    focusAreas: ['Appointments', 'Care team', 'Health records'],
  }),
  music_audio: createPreset({
    label: 'Music & Audio',
    defaultName: 'Music & Audio',
    defaultSlug: 'music-audio-app',
    primaryColor: '#7C3AED',
    harmony: 'triadic',
    summary: 'catalog browsing, playback, and creator discovery',
    focusAreas: ['Featured mixes', 'Recent listening', 'Creator spotlight'],
  }),
  navigation_travel: createPreset({
    label: 'Navigation & Travel',
    defaultName: 'Navigation & Travel',
    defaultSlug: 'navigation-travel-app',
    primaryColor: '#0284C7',
    harmony: 'analogous',
    summary: 'planning, routing, and trip operations',
    focusAreas: ['Trip planner', 'Saved places', 'Travel alerts'],
  }),
  news_magazines: createPreset({
    label: 'News & Magazines',
    defaultName: 'News & Magazines',
    defaultSlug: 'news-magazines-app',
    primaryColor: '#374151',
    harmony: 'monochromatic',
    summary: 'headlines, editorial curation, and subscriptions',
    focusAreas: ['Top stories', 'Topics', 'Saved articles'],
  }),
  photo_video: createPreset({
    label: 'Photo & Video',
    defaultName: 'Photo & Video',
    defaultSlug: 'photo-video-app',
    primaryColor: '#6D28D9',
    harmony: 'complementary',
    summary: 'capture flows, asset libraries, and publishing',
    focusAreas: ['Recent captures', 'Collections', 'Publishing queue'],
  }),
  reference: createPreset({
    label: 'Reference',
    defaultName: 'Reference',
    defaultSlug: 'reference-app',
    primaryColor: '#1D4ED8',
    harmony: 'monochromatic',
    summary: 'search, lookup, and structured knowledge discovery',
    focusAreas: ['Quick lookup', 'Saved resources', 'Reference sets'],
  }),
  shopping_commerce: createPreset({
    label: 'Shopping & Commerce',
    defaultName: 'Shopping & Commerce',
    defaultSlug: 'shopping-commerce-app',
    primaryColor: '#EA580C',
    harmony: 'analogous',
    summary: 'catalogs, carts, and fulfillment journeys',
    focusAreas: ['Featured products', 'Cart state', 'Order tracking'],
  }),
  social_community: createPreset({
    label: 'Social & Community',
    defaultName: 'Social & Community',
    defaultSlug: 'social-community-app',
    primaryColor: '#2563EB',
    harmony: 'complementary',
    summary: 'feeds, groups, and community participation',
    focusAreas: ['Community feed', 'Group highlights', 'Creator actions'],
  }),
  sports: createPreset({
    label: 'Sports',
    defaultName: 'Sports',
    defaultSlug: 'sports-app',
    primaryColor: '#DC2626',
    harmony: 'splitComplementary',
    summary: 'fixtures, scores, and fan engagement',
    focusAreas: ['Live schedule', 'Standings', 'Team updates'],
  }),
  utilities_tools: createPreset({
    label: 'Utilities & Tools',
    defaultName: 'Utilities & Tools',
    defaultSlug: 'utilities-tools-app',
    primaryColor: '#374151',
    harmony: 'monochromatic',
    summary: 'task-driven workflows, controls, and quick actions',
    focusAreas: ['Primary utilities', 'Saved shortcuts', 'Automation settings'],
  }),
  weather: createPreset({
    label: 'Weather',
    defaultName: 'Weather',
    defaultSlug: 'weather-app',
    primaryColor: '#0284C7',
    harmony: 'analogous',
    summary: 'conditions, alerts, and forecast planning',
    focusAreas: ['Current conditions', 'Hourly forecast', 'Alerts'],
  }),
};
