import type { CategoryPresetReconciliationSource } from './category-types';

export const CATEGORY_SOURCE_A = [
  {
    category: 'books_reading',
    existing: {
      label: 'Books & Reading',
      defaultName: 'Books & Reading',
      defaultSlug: 'books-reading-app',
      primaryColor: '#8B4513',
      harmony: 'analogous',
      summary: 'reading lists, reviews, recommendations, and subscriptions',
      focusAreas: ['Reading queue', 'Featured picks', 'Community notes'],
    },
    supplied: {
      designIntent: 'Scholarly, calm, long-form comfort',
      primaryColor: '#7C4A32',
      harmony: 'analogous',
      lightTonePair: 'earthy-on-pastel',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['Source Serif 4'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'soft',
    },
  },
  {
    category: 'business_productivity',
    existing: {
      label: 'Business & Productivity',
      defaultName: 'Business & Productivity',
      defaultSlug: 'business-productivity-app',
      primaryColor: '#1D4ED8',
      harmony: 'analogous',
      summary: 'team coordination, goals, and execution tracking',
      focusAreas: ['Active projects', 'Weekly priorities', 'Team updates'],
    },
    supplied: {
      designIntent: 'Focused, efficient, dependable',
      primaryColor: '#2563EB',
      harmony: 'monochromatic',
      lightTonePair: 'jewel-on-neutral-light',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['Inter'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'compact',
      shape: 'neutral',
    },
  },
  {
    category: 'developer_tools',
    existing: {
      label: 'Developer Tools',
      defaultName: 'Developer Tools',
      defaultSlug: 'developer-tools-app',
      primaryColor: '#7C3AED',
      harmony: 'triadic',
      summary: 'release workflows, observability, and engineering operations',
      focusAreas: ['Build status', 'Incident queue', 'Developer settings'],
    },
    supplied: {
      designIntent: 'Technical, precise, low-fatigue',
      primaryColor: '#0F766E',
      harmony: 'splitComplementary',
      lightTonePair: 'vivid-on-neutral-light',
      darkTonePair: 'fluorescent-on-neutral-dark',
      bodyFontCandidates: ['Inter'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [{ family: 'JetBrains Mono', usage: 'code' }],
      density: 'compact',
      shape: 'sharp',
    },
  },
  {
    category: 'education_learning',
    existing: {
      label: 'Education & Learning',
      defaultName: 'Education & Learning',
      defaultSlug: 'education-learning-app',
      primaryColor: '#4338CA',
      harmony: 'analogous',
      summary: 'courses, practice loops, and learner progress',
      focusAreas: ['Current lessons', 'Practice plan', 'Milestone tracking'],
    },
    supplied: {
      designIntent: 'Clear, encouraging, engaging',
      primaryColor: '#2563EB',
      harmony: 'triadic',
      lightTonePair: 'jewel-on-pastel',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['Atkinson Hyperlegible'],
      headingStrategy: 'auto-pair',
      headingFontCandidates: ['Outfit'],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'soft',
    },
  },
  {
    category: 'entertainment_media',
    existing: {
      label: 'Entertainment & Media',
      defaultName: 'Entertainment & Media',
      defaultSlug: 'entertainment-media-app',
      primaryColor: '#F97316',
      harmony: 'complementary',
      summary: 'content discovery, watchlists, and editorial highlights',
      focusAreas: ['Featured releases', 'Continue watching', 'Trending topics'],
    },
    supplied: {
      designIntent: 'Immersive, cinematic, expressive',
      primaryColor: '#E11D48',
      harmony: 'analogous',
      lightTonePair: 'vivid-on-neutral-light',
      darkTonePair: 'neon-on-neutral-dark',
      bodyFontCandidates: ['Inter'],
      headingStrategy: 'auto-pair',
      headingFontCandidates: ['Space Grotesk'],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'neutral',
    },
  },
  {
    category: 'finance_money',
    existing: {
      label: 'Finance & Money',
      defaultName: 'Finance & Money',
      defaultSlug: 'finance-money-app',
      primaryColor: '#15803D',
      harmony: 'analogous',
      summary: 'balances, budgeting, and financial operations',
      focusAreas: ['Cash overview', 'Budget health', 'Upcoming activity'],
    },
    supplied: {
      designIntent: 'Secure, rigorous, trustworthy',
      primaryColor: '#047857',
      harmony: 'complementary',
      lightTonePair: 'jewel-on-neutral-light',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['IBM Plex Sans'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'compact',
      shape: 'neutral',
    },
  },
  {
    category: 'food_drink',
    existing: {
      label: 'Food & Drink',
      defaultName: 'Food & Drink',
      defaultSlug: 'food-drink-app',
      primaryColor: '#EA580C',
      harmony: 'analogous',
      summary: 'menus, ordering, and loyalty experiences',
      focusAreas: ['Popular items', 'Order flow', 'Rewards status'],
    },
    supplied: {
      designIntent: 'Warm, appetizing, sensory',
      primaryColor: '#C2410C',
      harmony: 'analogous',
      lightTonePair: 'earthy-on-pastel',
      darkTonePair: 'bright-on-neutral-dark',
      bodyFontCandidates: ['Source Sans 3'],
      headingStrategy: 'auto-pair',
      headingFontCandidates: ['Fraunces'],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'soft',
    },
  },
  {
    category: 'games',
    existing: {
      label: 'Games',
      defaultName: 'Games',
      defaultSlug: 'games-app',
      primaryColor: '#7C3AED',
      harmony: 'splitComplementary',
      summary: 'quests, progression, and player engagement loops',
      focusAreas: ['Daily quests', 'Progression', 'Social challenges'],
    },
    supplied: {
      designIntent: 'Energetic, playful, state-rich',
      primaryColor: '#7C3AED',
      harmony: 'tetradic',
      lightTonePair: 'vivid-on-pastel',
      darkTonePair: 'neon-on-neutral-dark',
      bodyFontCandidates: ['Rubik'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'soft',
    },
  },
] as const satisfies readonly CategoryPresetReconciliationSource[];
