import type { CategoryPresetReconciliationSource } from './category-types';

export const CATEGORY_SOURCE_C = [
  {
    category: 'photo_video',
    existing: {
      label: 'Photo & Video',
      defaultName: 'Photo & Video',
      defaultSlug: 'photo-video-app',
      primaryColor: '#6D28D9',
      harmony: 'complementary',
      summary: 'capture flows, asset libraries, and publishing',
      focusAreas: ['Recent captures', 'Collections', 'Publishing queue'],
    },
    supplied: {
      designIntent: 'Quiet framing with media priority',
      primaryColor: '#6D28D9',
      harmony: 'monochromatic',
      lightTonePair: 'muted-on-neutral-light',
      darkTonePair: 'ice-on-neutral-dark',
      bodyFontCandidates: ['Inter'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'compact',
      shape: 'neutral',
    },
  },
  {
    category: 'reference',
    existing: {
      label: 'Reference',
      defaultName: 'Reference',
      defaultSlug: 'reference-app',
      primaryColor: '#1D4ED8',
      harmony: 'monochromatic',
      summary: 'search, lookup, and structured knowledge discovery',
      focusAreas: ['Quick lookup', 'Saved resources', 'Reference sets'],
    },
    supplied: {
      designIntent: 'Objective, dense, highly readable',
      primaryColor: '#475569',
      harmony: 'monochromatic',
      lightTonePair: 'muted-on-neutral-light',
      darkTonePair: 'ice-on-neutral-dark',
      bodyFontCandidates: ['Source Sans 3'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'compact',
      shape: 'sharp',
    },
  },
  {
    category: 'shopping_commerce',
    existing: {
      label: 'Shopping & Commerce',
      defaultName: 'Shopping & Commerce',
      defaultSlug: 'shopping-commerce-app',
      primaryColor: '#EA580C',
      harmony: 'analogous',
      summary: 'catalogs, carts, and fulfillment journeys',
      focusAreas: ['Featured products', 'Cart state', 'Order tracking'],
    },
    supplied: {
      designIntent: 'Conversion-focused, confident',
      primaryColor: '#7C3AED',
      harmony: 'complementary',
      lightTonePair: 'jewel-on-neutral-light',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['DM Sans'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'neutral',
    },
  },
  {
    category: 'social_community',
    existing: {
      label: 'Social & Community',
      defaultName: 'Social & Community',
      defaultSlug: 'social-community-app',
      primaryColor: '#2563EB',
      harmony: 'complementary',
      summary: 'feeds, groups, and community participation',
      focusAreas: ['Community feed', 'Group highlights', 'Creator actions'],
    },
    supplied: {
      designIntent: 'Friendly, collaborative, lively',
      primaryColor: '#4F46E5',
      harmony: 'analogous',
      lightTonePair: 'vivid-on-pastel',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['Inter'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'soft',
    },
  },
  {
    category: 'sports',
    existing: {
      label: 'Sports',
      defaultName: 'Sports',
      defaultSlug: 'sports-app',
      primaryColor: '#DC2626',
      harmony: 'splitComplementary',
      summary: 'fixtures, scores, and fan engagement',
      focusAreas: ['Live schedule', 'Standings', 'Team updates'],
    },
    supplied: {
      designIntent: 'Fast, forceful, movement-led',
      primaryColor: '#DC2626',
      harmony: 'splitComplementary',
      lightTonePair: 'vivid-on-neutral-light',
      darkTonePair: 'neon-on-neutral-dark',
      bodyFontCandidates: ['Archivo'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'compact',
      shape: 'sharp',
    },
  },
  {
    category: 'utilities_tools',
    existing: {
      label: 'Utilities & Tools',
      defaultName: 'Utilities & Tools',
      defaultSlug: 'utilities-tools-app',
      primaryColor: '#374151',
      harmony: 'monochromatic',
      summary: 'task-driven workflows, controls, and quick actions',
      focusAreas: ['Primary utilities', 'Saved shortcuts', 'Automation settings'],
    },
    supplied: {
      designIntent: 'Functional, restrained, efficient',
      primaryColor: '#475569',
      harmony: 'monochromatic',
      lightTonePair: 'muted-on-neutral-light',
      darkTonePair: 'ice-on-neutral-dark',
      bodyFontCandidates: ['Inter'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'compact',
      shape: 'neutral',
    },
  },
  {
    category: 'weather',
    existing: {
      label: 'Weather',
      defaultName: 'Weather',
      defaultSlug: 'weather-app',
      primaryColor: '#0284C7',
      harmony: 'analogous',
      summary: 'conditions, alerts, and forecast planning',
      focusAreas: ['Current conditions', 'Hourly forecast', 'Alerts'],
    },
    supplied: {
      designIntent: 'Atmospheric, ambient, glanceable',
      primaryColor: '#2563EB',
      harmony: 'analogous',
      lightTonePair: 'vivid-on-ice',
      darkTonePair: 'ice-on-neutral-dark',
      bodyFontCandidates: ['Manrope'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'soft',
    },
  },
] as const satisfies readonly CategoryPresetReconciliationSource[];
