import type { CategoryPresetReconciliationSource } from './category-types';

export const CATEGORY_SOURCE_B = [
  {
    category: 'graphics_design',
    existing: {
      label: 'Graphics & Design',
      defaultName: 'Graphics & Design',
      defaultSlug: 'graphics-design-app',
      primaryColor: '#9333EA',
      harmony: 'triadic',
      summary: 'creative assets, reviews, and delivery workflows',
      focusAreas: ['Current briefs', 'Asset review', 'Brand tokens'],
    },
    supplied: {
      designIntent: 'Creative, exact, tool-oriented',
      primaryColor: '#DB2777',
      harmony: 'complementary',
      lightTonePair: 'vivid-on-neutral-light',
      darkTonePair: 'neon-on-neutral-dark',
      bodyFontCandidates: ['Space Grotesk'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'compact',
      shape: 'neutral',
    },
  },
  {
    category: 'health_fitness',
    existing: {
      label: 'Health & Fitness',
      defaultName: 'Health & Fitness',
      defaultSlug: 'health-fitness-app',
      primaryColor: '#059669',
      harmony: 'analogous',
      summary: 'habits, activity tracking, and coaching plans',
      focusAreas: ['Today plan', 'Progress rings', 'Recovery status'],
    },
    supplied: {
      designIntent: 'Vital, clean, motivating',
      primaryColor: '#059669',
      harmony: 'analogous',
      lightTonePair: 'jewel-on-ice',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['Source Sans 3'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'soft',
    },
  },
  {
    category: 'kids_family',
    existing: {
      label: 'Kids & Family',
      defaultName: 'Kids & Family',
      defaultSlug: 'kids-family-app',
      primaryColor: '#F97316',
      harmony: 'splitComplementary',
      summary: 'safe discovery, routines, and shared family coordination',
      focusAreas: ['Daily routines', 'Favorites', 'Parent controls'],
    },
    supplied: {
      designIntent: 'Safe, cheerful, legible',
      primaryColor: '#D97706',
      harmony: 'triadic',
      lightTonePair: 'vivid-on-pastel',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['Nunito'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'spacious',
      shape: 'soft',
    },
  },
  {
    category: 'lifestyle',
    existing: {
      label: 'Lifestyle',
      defaultName: 'Lifestyle',
      defaultSlug: 'lifestyle-app',
      primaryColor: '#DB2777',
      harmony: 'analogous',
      summary: 'memberships, routines, and curated recommendations',
      focusAreas: ['Personal dashboard', 'Saved lists', 'Upcoming plans'],
    },
    supplied: {
      designIntent: 'Curated, editorial, warm',
      primaryColor: '#9A4E36',
      harmony: 'analogous',
      lightTonePair: 'muted-on-pastel',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['Manrope'],
      headingStrategy: 'auto-pair',
      headingFontCandidates: ['Cormorant Garamond'],
      specialistFontCandidates: [],
      density: 'spacious',
      shape: 'soft',
    },
  },
  {
    category: 'medical',
    existing: {
      label: 'Medical',
      defaultName: 'Medical',
      defaultSlug: 'medical-app',
      primaryColor: '#0369A1',
      harmony: 'analogous',
      summary: 'care coordination, intake, and patient communication',
      focusAreas: ['Appointments', 'Care team', 'Health records'],
    },
    supplied: {
      designIntent: 'Clinical, calm, unambiguous',
      primaryColor: '#0284C7',
      harmony: 'monochromatic',
      lightTonePair: 'jewel-on-ice',
      darkTonePair: 'ice-on-neutral-dark',
      bodyFontCandidates: ['Atkinson Hyperlegible'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'neutral',
    },
  },
  {
    category: 'music_audio',
    existing: {
      label: 'Music & Audio',
      defaultName: 'Music & Audio',
      defaultSlug: 'music-audio-app',
      primaryColor: '#7C3AED',
      harmony: 'triadic',
      summary: 'catalog browsing, playback, and creator discovery',
      focusAreas: ['Featured mixes', 'Recent listening', 'Creator spotlight'],
    },
    supplied: {
      designIntent: 'Rhythmic, immersive, high-energy',
      primaryColor: '#9333EA',
      harmony: 'splitComplementary',
      lightTonePair: 'vivid-on-neutral-light',
      darkTonePair: 'neon-on-neutral-dark',
      bodyFontCandidates: ['Space Grotesk'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'neutral',
    },
  },
  {
    category: 'navigation_travel',
    existing: {
      label: 'Navigation & Travel',
      defaultName: 'Navigation & Travel',
      defaultSlug: 'navigation-travel-app',
      primaryColor: '#0284C7',
      harmony: 'analogous',
      summary: 'planning, routing, and trip operations',
      focusAreas: ['Trip planner', 'Saved places', 'Travel alerts'],
    },
    supplied: {
      designIntent: 'Clear, adventurous, situational',
      primaryColor: '#0284C7',
      harmony: 'analogous',
      lightTonePair: 'jewel-on-pastel',
      darkTonePair: 'bright-on-neutral-dark',
      bodyFontCandidates: ['Manrope'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'neutral',
    },
  },
  {
    category: 'news_magazines',
    existing: {
      label: 'News & Magazines',
      defaultName: 'News & Magazines',
      defaultSlug: 'news-magazines-app',
      primaryColor: '#374151',
      harmony: 'monochromatic',
      summary: 'headlines, editorial curation, and subscriptions',
      focusAreas: ['Top stories', 'Topics', 'Saved articles'],
    },
    supplied: {
      designIntent: 'Editorial, credible, scannable',
      primaryColor: '#B91C1C',
      harmony: 'complementary',
      lightTonePair: 'jewel-on-neutral-light',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['Source Serif 4'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'compact',
      shape: 'sharp',
    },
  },
] as const satisfies readonly CategoryPresetReconciliationSource[];
