import type { CategoryPresetReconciliationSource } from './category-types';

export const CATEGORY_SOURCE = [
  {
    category: 'books_reading',
    existing: {
      label: 'Books & Reading',
      defaultName: 'Books & Reading',
      defaultSlug: 'books-reading-app',
      primaryColor: '#8B4513',
      harmony: 'analogous',
      summary: 'reading lists, reviews, recommendations, and subscriptions',
      focusAreas: ['Reading queue', 'Featured picks', 'Community notes'],
    },
    supplied: {
      designIntent: 'Scholarly, calm, long-form comfort',
      primaryColor: '#7C4A32',
      harmony: 'analogous',
      lightTonePair: 'earthy-on-pastel',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['Source Serif 4'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'soft',
    },
  },
  {
    category: 'business_productivity',
    existing: {
      label: 'Business & Productivity',
      defaultName: 'Business & Productivity',
      defaultSlug: 'business-productivity-app',
      primaryColor: '#1D4ED8',
      harmony: 'analogous',
      summary: 'team coordination, goals, and execution tracking',
      focusAreas: ['Active projects', 'Weekly priorities', 'Team updates'],
    },
    supplied: {
      designIntent: 'Focused, efficient, dependable',
      primaryColor: '#2563EB',
      harmony: 'monochromatic',
      lightTonePair: 'jewel-on-neutral-light',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['Inter'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'compact',
      shape: 'neutral',
    },
  },
  {
    category: 'developer_tools',
    existing: {
      label: 'Developer Tools',
      defaultName: 'Developer Tools',
      defaultSlug: 'developer-tools-app',
      primaryColor: '#7C3AED',
      harmony: 'triadic',
      summary: 'release workflows, observability, and engineering operations',
      focusAreas: ['Build status', 'Incident queue', 'Developer settings'],
    },
    supplied: {
      designIntent: 'Technical, precise, low-fatigue',
      primaryColor: '#0F766E',
      harmony: 'splitComplementary',
      lightTonePair: 'vivid-on-neutral-light',
      darkTonePair: 'fluorescent-on-neutral-dark',
      bodyFontCandidates: ['Inter'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [{ family: 'JetBrains Mono', usage: 'code' }],
      density: 'compact',
      shape: 'sharp',
    },
  },
  {
    category: 'education_learning',
    existing: {
      label: 'Education & Learning',
      defaultName: 'Education & Learning',
      defaultSlug: 'education-learning-app',
      primaryColor: '#4338CA',
      harmony: 'analogous',
      summary: 'courses, practice loops, and learner progress',
      focusAreas: ['Current lessons', 'Practice plan', 'Milestone tracking'],
    },
    supplied: {
      designIntent: 'Clear, encouraging, engaging',
      primaryColor: '#2563EB',
      harmony: 'triadic',
      lightTonePair: 'jewel-on-pastel',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['Atkinson Hyperlegible'],
      headingStrategy: 'auto-pair',
      headingFontCandidates: ['Outfit'],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'soft',
    },
  },
  {
    category: 'entertainment_media',
    existing: {
      label: 'Entertainment & Media',
      defaultName: 'Entertainment & Media',
      defaultSlug: 'entertainment-media-app',
      primaryColor: '#F97316',
      harmony: 'complementary',
      summary: 'content discovery, watchlists, and editorial highlights',
      focusAreas: ['Featured releases', 'Continue watching', 'Trending topics'],
    },
    supplied: {
      designIntent: 'Immersive, cinematic, expressive',
      primaryColor: '#E11D48',
      harmony: 'analogous',
      lightTonePair: 'vivid-on-neutral-light',
      darkTonePair: 'neon-on-neutral-dark',
      bodyFontCandidates: ['Inter'],
      headingStrategy: 'auto-pair',
      headingFontCandidates: ['Space Grotesk'],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'neutral',
    },
  },
  {
    category: 'finance_money',
    existing: {
      label: 'Finance & Money',
      defaultName: 'Finance & Money',
      defaultSlug: 'finance-money-app',
      primaryColor: '#15803D',
      harmony: 'analogous',
      summary: 'balances, budgeting, and financial operations',
      focusAreas: ['Cash overview', 'Budget health', 'Upcoming activity'],
    },
    supplied: {
      designIntent: 'Secure, rigorous, trustworthy',
      primaryColor: '#047857',
      harmony: 'complementary',
      lightTonePair: 'jewel-on-neutral-light',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['IBM Plex Sans'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'compact',
      shape: 'neutral',
    },
  },
  {
    category: 'food_drink',
    existing: {
      label: 'Food & Drink',
      defaultName: 'Food & Drink',
      defaultSlug: 'food-drink-app',
      primaryColor: '#EA580C',
      harmony: 'analogous',
      summary: 'menus, ordering, and loyalty experiences',
      focusAreas: ['Popular items', 'Order flow', 'Rewards status'],
    },
    supplied: {
      designIntent: 'Warm, appetizing, sensory',
      primaryColor: '#C2410C',
      harmony: 'analogous',
      lightTonePair: 'earthy-on-pastel',
      darkTonePair: 'bright-on-neutral-dark',
      bodyFontCandidates: ['Source Sans 3'],
      headingStrategy: 'auto-pair',
      headingFontCandidates: ['Fraunces'],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'soft',
    },
  },
  {
    category: 'games',
    existing: {
      label: 'Games',
      defaultName: 'Games',
      defaultSlug: 'games-app',
      primaryColor: '#7C3AED',
      harmony: 'splitComplementary',
      summary: 'quests, progression, and player engagement loops',
      focusAreas: ['Daily quests', 'Progression', 'Social challenges'],
    },
    supplied: {
      designIntent: 'Energetic, playful, state-rich',
      primaryColor: '#7C3AED',
      harmony: 'tetradic',
      lightTonePair: 'vivid-on-pastel',
      darkTonePair: 'neon-on-neutral-dark',
      bodyFontCandidates: ['Rubik'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'soft',
    },
  },
  {
    category: 'graphics_design',
    existing: {
      label: 'Graphics & Design',
      defaultName: 'Graphics & Design',
      defaultSlug: 'graphics-design-app',
      primaryColor: '#9333EA',
      harmony: 'triadic',
      summary: 'creative assets, reviews, and delivery workflows',
      focusAreas: ['Current briefs', 'Asset review', 'Brand tokens'],
    },
    supplied: {
      designIntent: 'Creative, exact, tool-oriented',
      primaryColor: '#DB2777',
      harmony: 'complementary',
      lightTonePair: 'vivid-on-neutral-light',
      darkTonePair: 'neon-on-neutral-dark',
      bodyFontCandidates: ['Space Grotesk'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'compact',
      shape: 'neutral',
    },
  },
  {
    category: 'health_fitness',
    existing: {
      label: 'Health & Fitness',
      defaultName: 'Health & Fitness',
      defaultSlug: 'health-fitness-app',
      primaryColor: '#059669',
      harmony: 'analogous',
      summary: 'habits, activity tracking, and coaching plans',
      focusAreas: ['Today plan', 'Progress rings', 'Recovery status'],
    },
    supplied: {
      designIntent: 'Vital, clean, motivating',
      primaryColor: '#059669',
      harmony: 'analogous',
      lightTonePair: 'jewel-on-ice',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['Source Sans 3'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'soft',
    },
  },
  {
    category: 'kids_family',
    existing: {
      label: 'Kids & Family',
      defaultName: 'Kids & Family',
      defaultSlug: 'kids-family-app',
      primaryColor: '#F97316',
      harmony: 'splitComplementary',
      summary: 'safe discovery, routines, and shared family coordination',
      focusAreas: ['Daily routines', 'Favorites', 'Parent controls'],
    },
    supplied: {
      designIntent: 'Safe, cheerful, legible',
      primaryColor: '#D97706',
      harmony: 'triadic',
      lightTonePair: 'vivid-on-pastel',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['Nunito'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'spacious',
      shape: 'soft',
    },
  },
  {
    category: 'lifestyle',
    existing: {
      label: 'Lifestyle',
      defaultName: 'Lifestyle',
      defaultSlug: 'lifestyle-app',
      primaryColor: '#DB2777',
      harmony: 'analogous',
      summary: 'memberships, routines, and curated recommendations',
      focusAreas: ['Personal dashboard', 'Saved lists', 'Upcoming plans'],
    },
    supplied: {
      designIntent: 'Curated, editorial, warm',
      primaryColor: '#9A4E36',
      harmony: 'analogous',
      lightTonePair: 'muted-on-pastel',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['Manrope'],
      headingStrategy: 'auto-pair',
      headingFontCandidates: ['Cormorant Garamond'],
      specialistFontCandidates: [],
      density: 'spacious',
      shape: 'soft',
    },
  },
  {
    category: 'medical',
    existing: {
      label: 'Medical',
      defaultName: 'Medical',
      defaultSlug: 'medical-app',
      primaryColor: '#0369A1',
      harmony: 'analogous',
      summary: 'care coordination, intake, and patient communication',
      focusAreas: ['Appointments', 'Care team', 'Health records'],
    },
    supplied: {
      designIntent: 'Clinical, calm, unambiguous',
      primaryColor: '#0284C7',
      harmony: 'monochromatic',
      lightTonePair: 'jewel-on-ice',
      darkTonePair: 'ice-on-neutral-dark',
      bodyFontCandidates: ['Atkinson Hyperlegible'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'neutral',
    },
  },
  {
    category: 'music_audio',
    existing: {
      label: 'Music & Audio',
      defaultName: 'Music & Audio',
      defaultSlug: 'music-audio-app',
      primaryColor: '#7C3AED',
      harmony: 'triadic',
      summary: 'catalog browsing, playback, and creator discovery',
      focusAreas: ['Featured mixes', 'Recent listening', 'Creator spotlight'],
    },
    supplied: {
      designIntent: 'Rhythmic, immersive, high-energy',
      primaryColor: '#9333EA',
      harmony: 'splitComplementary',
      lightTonePair: 'vivid-on-neutral-light',
      darkTonePair: 'neon-on-neutral-dark',
      bodyFontCandidates: ['Space Grotesk'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'neutral',
    },
  },
  {
    category: 'navigation_travel',
    existing: {
      label: 'Navigation & Travel',
      defaultName: 'Navigation & Travel',
      defaultSlug: 'navigation-travel-app',
      primaryColor: '#0284C7',
      harmony: 'analogous',
      summary: 'planning, routing, and trip operations',
      focusAreas: ['Trip planner', 'Saved places', 'Travel alerts'],
    },
    supplied: {
      designIntent: 'Clear, adventurous, situational',
      primaryColor: '#0284C7',
      harmony: 'analogous',
      lightTonePair: 'jewel-on-pastel',
      darkTonePair: 'bright-on-neutral-dark',
      bodyFontCandidates: ['Manrope'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'neutral',
    },
  },
  {
    category: 'news_magazines',
    existing: {
      label: 'News & Magazines',
      defaultName: 'News & Magazines',
      defaultSlug: 'news-magazines-app',
      primaryColor: '#374151',
      harmony: 'monochromatic',
      summary: 'headlines, editorial curation, and subscriptions',
      focusAreas: ['Top stories', 'Topics', 'Saved articles'],
    },
    supplied: {
      designIntent: 'Editorial, credible, scannable',
      primaryColor: '#B91C1C',
      harmony: 'complementary',
      lightTonePair: 'jewel-on-neutral-light',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['Source Serif 4'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'compact',
      shape: 'sharp',
    },
  },
  {
    category: 'photo_video',
    existing: {
      label: 'Photo & Video',
      defaultName: 'Photo & Video',
      defaultSlug: 'photo-video-app',
      primaryColor: '#6D28D9',
      harmony: 'complementary',
      summary: 'capture flows, asset libraries, and publishing',
      focusAreas: ['Recent captures', 'Collections', 'Publishing queue'],
    },
    supplied: {
      designIntent: 'Quiet framing with media priority',
      primaryColor: '#6D28D9',
      harmony: 'monochromatic',
      lightTonePair: 'muted-on-neutral-light',
      darkTonePair: 'ice-on-neutral-dark',
      bodyFontCandidates: ['Inter'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'compact',
      shape: 'neutral',
    },
  },
  {
    category: 'reference',
    existing: {
      label: 'Reference',
      defaultName: 'Reference',
      defaultSlug: 'reference-app',
      primaryColor: '#1D4ED8',
      harmony: 'monochromatic',
      summary: 'search, lookup, and structured knowledge discovery',
      focusAreas: ['Quick lookup', 'Saved resources', 'Reference sets'],
    },
    supplied: {
      designIntent: 'Objective, dense, highly readable',
      primaryColor: '#475569',
      harmony: 'monochromatic',
      lightTonePair: 'muted-on-neutral-light',
      darkTonePair: 'ice-on-neutral-dark',
      bodyFontCandidates: ['Source Sans 3'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'compact',
      shape: 'sharp',
    },
  },
  {
    category: 'shopping_commerce',
    existing: {
      label: 'Shopping & Commerce',
      defaultName: 'Shopping & Commerce',
      defaultSlug: 'shopping-commerce-app',
      primaryColor: '#EA580C',
      harmony: 'analogous',
      summary: 'catalogs, carts, and fulfillment journeys',
      focusAreas: ['Featured products', 'Cart state', 'Order tracking'],
    },
    supplied: {
      designIntent: 'Conversion-focused, confident',
      primaryColor: '#7C3AED',
      harmony: 'complementary',
      lightTonePair: 'jewel-on-neutral-light',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['DM Sans'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'neutral',
    },
  },
  {
    category: 'social_community',
    existing: {
      label: 'Social & Community',
      defaultName: 'Social & Community',
      defaultSlug: 'social-community-app',
      primaryColor: '#2563EB',
      harmony: 'complementary',
      summary: 'feeds, groups, and community participation',
      focusAreas: ['Community feed', 'Group highlights', 'Creator actions'],
    },
    supplied: {
      designIntent: 'Friendly, collaborative, lively',
      primaryColor: '#4F46E5',
      harmony: 'analogous',
      lightTonePair: 'vivid-on-pastel',
      darkTonePair: 'pastel-on-neutral-dark',
      bodyFontCandidates: ['Inter'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'soft',
    },
  },
  {
    category: 'sports',
    existing: {
      label: 'Sports',
      defaultName: 'Sports',
      defaultSlug: 'sports-app',
      primaryColor: '#DC2626',
      harmony: 'splitComplementary',
      summary: 'fixtures, scores, and fan engagement',
      focusAreas: ['Live schedule', 'Standings', 'Team updates'],
    },
    supplied: {
      designIntent: 'Fast, forceful, movement-led',
      primaryColor: '#DC2626',
      harmony: 'splitComplementary',
      lightTonePair: 'vivid-on-neutral-light',
      darkTonePair: 'neon-on-neutral-dark',
      bodyFontCandidates: ['Archivo'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'compact',
      shape: 'sharp',
    },
  },
  {
    category: 'utilities_tools',
    existing: {
      label: 'Utilities & Tools',
      defaultName: 'Utilities & Tools',
      defaultSlug: 'utilities-tools-app',
      primaryColor: '#374151',
      harmony: 'monochromatic',
      summary: 'task-driven workflows, controls, and quick actions',
      focusAreas: ['Primary utilities', 'Saved shortcuts', 'Automation settings'],
    },
    supplied: {
      designIntent: 'Functional, restrained, efficient',
      primaryColor: '#475569',
      harmony: 'monochromatic',
      lightTonePair: 'muted-on-neutral-light',
      darkTonePair: 'ice-on-neutral-dark',
      bodyFontCandidates: ['Inter'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'compact',
      shape: 'neutral',
    },
  },
  {
    category: 'weather',
    existing: {
      label: 'Weather',
      defaultName: 'Weather',
      defaultSlug: 'weather-app',
      primaryColor: '#0284C7',
      harmony: 'analogous',
      summary: 'conditions, alerts, and forecast planning',
      focusAreas: ['Current conditions', 'Hourly forecast', 'Alerts'],
    },
    supplied: {
      designIntent: 'Atmospheric, ambient, glanceable',
      primaryColor: '#2563EB',
      harmony: 'analogous',
      lightTonePair: 'vivid-on-ice',
      darkTonePair: 'ice-on-neutral-dark',
      bodyFontCandidates: ['Manrope'],
      headingStrategy: 'same',
      headingFontCandidates: [],
      specialistFontCandidates: [],
      density: 'comfortable',
      shape: 'soft',
    },
  },
] as const satisfies readonly CategoryPresetReconciliationSource[];
