export {
  assertTemplateManifestReady,
  type CategoryAppManifestComposition,
  composeCategoryAppManifest,
  type ComposeCategoryAppManifestInput,
  type TemplateAuthoringState,
  type TemplateCompositionDiagnostic,
  type TemplateCompositionDiagnosticCode,
  type TemplateCompositionStatus,
  validateTemplateManifest,
} from './authoring/compose-category-manifest';
export {
  type CategoryDesignDiagnostic,
  type CategoryDesignDiagnosticCode,
  type CategoryDesignOverrides,
  compileCategoryDesign,
  type CompiledCategoryDesign,
  resolveCategoryDesignPreset,
  type ResolvedCategoryDesignPreset,
} from './design/category-theme';
export {
  DESIGN_DENSITIES,
  DESIGN_SHAPES,
  type DesignDensity,
  type DesignShape,
} from './design/category-types';
export {
  ACCENT_TONE_FAMILIES,
  ACCENT_TONE_TARGETS,
  type AccentToneFamily,
  FOUNDATION_TONE_FAMILIES,
  FOUNDATION_TONE_TARGETS,
  type FoundationToneFamily,
  resolveTonePair,
  type ThemeMode,
  TONE_PAIR_CATALOG,
  type TonePairClassification,
  type TonePairDefinition,
  type TonePairId,
  type ToneTarget,
} from './design/tone-catalog';
export {
  createOAuthFixtureManifest,
  listOAuthFixtures,
  OAUTH_CALLBACK_ROUTE,
  OAUTH_FIXTURE_IDS,
  type OAuthFixtureDefinition,
  type OAuthFixtureId,
  resolveOAuthFixture,
} from './fixtures/oauth';
export { createCategoryAppManifest } from './generators/create-category-app';
export {
  CATEGORY_PRESET_RECONCILIATION,
  CATEGORY_PRESETS,
  type CategoryPreset,
  type CategoryPresetFieldReconciliation,
  type CategoryPresetReconciliationDecision,
  type CategoryPresetReconciliationReport,
} from './presets/category-presets';
export {
  type CategoryStarterTemplateDefinition,
  createStarterTemplate,
  createStarterTemplateArtifact,
  listStarterTemplates,
  listStarterTemplatesByCategory,
  listStarterTemplateSummaries,
  resolveStarterTemplate,
  type StarterTemplateArtifact,
  type StarterTemplateAsset,
  type StarterTemplateAssetSummary,
  type StarterTemplateFactory,
  type StarterTemplateId,
  type StarterTemplateOptions,
  type StarterTemplateResult,
  type StarterTemplateSelection,
  type StarterTemplateSummary,
  summarizeStarterTemplateAssets,
  TEMPLATE_IMAGE_CONTENT_TYPES,
  TEMPLATE_KINDS,
  type TemplateImageContentType,
  type TemplateKind,
  type TemplateSeed,
  validateStarterTemplateAssets,
} from './templates/starter';
export {
  APP_CATEGORIES,
  type AppCategory,
  type SplashScreenResizeMode,
  type SplashScreenSpec,
} from '@ankhorage/contracts';
